//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadEndDynamicXpath.PageUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CaasBaseUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaasBaseUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeadEndDynamicXpath.PageUI.CaasBaseUI", typeof(CaasBaseUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Metering Manager.
        /// </summary>
        internal static string AMM {
            get {
                return ResourceManager.GetString("AMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Authentication/Authorization Server.
        /// </summary>
        internal static string CAS {
            get {
                return ResourceManager.GetString("CAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Groups.
        /// </summary>
        internal static string DeviceGroups {
            get {
                return ResourceManager.GetString("DeviceGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Upgrader.
        /// </summary>
        internal static string FWU {
            get {
                return ResourceManager.GetString("FWU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Program Configurator.
        /// </summary>
        internal static string MPC {
            get {
                return ResourceManager.GetString("MPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Center.
        /// </summary>
        internal static string NC {
            get {
                return ResourceManager.GetString("NC", resourceCulture);
            }
        }
    }
}
