//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadEndDynamicXpath.PageXpaths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AbstractComponent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AbstractComponent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeadEndDynamicXpath.PageXpaths.AbstractComponent", typeof(AbstractComponent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[normalize-space()=&apos;Acccess Point Success Rate: ≤&apos;].
        /// </summary>
        internal static string AccessPointSuccessRate {
            get {
                return ResourceManager.GetString("AccessPointSuccessRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;successRate&apos; and @value=&apos;100&apos;].
        /// </summary>
        internal static string AccessPointSuccessRateValue {
            get {
                return ResourceManager.GetString("AccessPointSuccessRateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;pagination&apos;]//tr//td[@class=&apos;tal&apos;].
        /// </summary>
        internal static string ColumnCount {
            get {
                return ResourceManager.GetString("ColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //img[@title=&apos;Add a New Report&apos;]/ancestor::a.
        /// </summary>
        internal static string CreateCustomReport_Link {
            get {
                return ResourceManager.GetString("CreateCustomReport_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[normalize-space()=&apos;dynamic&apos;].
        /// </summary>
        internal static string CreateReport_link {
            get {
                return ResourceManager.GetString("CreateReport_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ssnui-headerSubNav&apos;]//a[normalize-space()=&apos;dynamic&apos;].
        /// </summary>
        internal static string CreateReport_SubTabLink {
            get {
                return ResourceManager.GetString("CreateReport_SubTabLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;mll fs11&apos;].
        /// </summary>
        internal static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@class=&apos;timePickerAmPm&apos;]//select.
        /// </summary>
        internal static string Datepicker_AMPMSelect {
            get {
                return ResourceManager.GetString("Datepicker_AMPMSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@class=&apos;timePickerAmPm&apos;]/select[@id=&apos;end_time_DatePicker_0_amPmMenu&apos;].
        /// </summary>
        internal static string Datepicker_AMPMSelect_EndDate {
            get {
                return ResourceManager.GetString("Datepicker_AMPMSelect_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;Clear&apos;].
        /// </summary>
        internal static string Datepicker_ClearLink {
            get {
                return ResourceManager.GetString("Datepicker_ClearLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[@class=&apos;datePickerWeek&apos;]//td[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string Datepicker_Day {
            get {
                return ResourceManager.GetString("Datepicker_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@id=&apos;end_time_DatePicker_0_calYearLink&apos;]//following::tr[@class=&apos;datePickerWeek&apos;]//td[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string Datepicker_Day_EndDate {
            get {
                return ResourceManager.GetString("Datepicker_Day_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@id=&apos;end_time_DatePicker_0_clearButton&apos;].
        /// </summary>
        internal static string DatePicker_EndDate_Clear {
            get {
                return ResourceManager.GetString("DatePicker_EndDate_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@class=&apos;timePickerHours&apos;]//select.
        /// </summary>
        internal static string Datepicker_hourSelect {
            get {
                return ResourceManager.GetString("Datepicker_hourSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@class=&apos;timePickerHours&apos;]/select[@id=&apos;end_time_DatePicker_0_hoursMenu&apos;].
        /// </summary>
        internal static string Datepicker_hourSelect_EndDate {
            get {
                return ResourceManager.GetString("Datepicker_hourSelect_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@class=&apos;timePickerMinutes&apos;]//select.
        /// </summary>
        internal static string Datepicker_MinSelect {
            get {
                return ResourceManager.GetString("Datepicker_MinSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@class=&apos;timePickerMinutes&apos;]/select[@id=&apos;end_time_DatePicker_0_minutesMenu&apos;].
        /// </summary>
        internal static string Datepicker_MinSelect_EndDate {
            get {
                return ResourceManager.GetString("Datepicker_MinSelect_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;datePickerCal&apos;]//a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string Datepicker_Month {
            get {
                return ResourceManager.GetString("Datepicker_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;datePickerCalContainer&apos;]//a[contains(@id,&apos;end_time&apos;) and text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string Datepicker_Month_EndDate {
            get {
                return ResourceManager.GetString("Datepicker_Month_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;datePickerMonthCell&apos;].
        /// </summary>
        internal static string Datepicker_MonthCell {
            get {
                return ResourceManager.GetString("Datepicker_MonthCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@id=&apos;end_time_DatePicker_0_calMonthLink&apos; and text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string Datepicker_MonthCell_EndDate {
            get {
                return ResourceManager.GetString("Datepicker_MonthCell_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;OK&apos;].
        /// </summary>
        internal static string Datepicker_OKLink {
            get {
                return ResourceManager.GetString("Datepicker_OKLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(@id,&apos;end_time&apos;) and text()=&apos;OK&apos;].
        /// </summary>
        internal static string Datepicker_OKLink_EndDate {
            get {
                return ResourceManager.GetString("Datepicker_OKLink_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;datePickerYearOptions&apos;]//a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string Datepicker_Year {
            get {
                return ResourceManager.GetString("Datepicker_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;datePickerYearOptions&apos;]/a[contains(@id,&apos;end_time&apos;) and text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string DatePicker_Year_EndDate {
            get {
                return ResourceManager.GetString("DatePicker_Year_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;datePickerYearCell&apos;]//a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string Datepicker_YearCell {
            get {
                return ResourceManager.GetString("Datepicker_YearCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@id=&apos;end_time_DatePicker_0_calYearLink&apos; and text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string DatePicker_YearCell_EndDate {
            get {
                return ResourceManager.GetString("DatePicker_YearCell_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[text()=&apos;Decimal Precision:&apos;]/span.
        /// </summary>
        internal static string Decimal_Precision_label {
            get {
                return ResourceManager.GetString("Decimal_Precision_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[text()=&apos;End Date:&apos;]/following-sibling::span/a.
        /// </summary>
        internal static string EndDate_Link {
            get {
                return ResourceManager.GetString("EndDate_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@class=&apos;btn btnTiny buttonFiles&apos;].
        /// </summary>
        internal static string FileButton {
            get {
                return ResourceManager.GetString("FileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;pts&apos;]//a//img[@alt=&apos;Uncompressed File&apos;].
        /// </summary>
        internal static string FileDownload {
            get {
                return ResourceManager.GetString("FileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;pts&apos;].
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;rr_table&apos;]//td[@class=&apos;nowrap&apos;].
        /// </summary>
        internal static string GDT_Date {
            get {
                return ResourceManager.GetString("GDT_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(text(),&apos;Gas Day Take Data Report&apos;)].
        /// </summary>
        internal static string GDT_PageTitle {
            get {
                return ResourceManager.GetString("GDT_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;rr_table&apos;]//span[normalize-space()=&apos;Gas Day Take Read Success&apos;].
        /// </summary>
        internal static string GDT_SuccessRead_Table_Title {
            get {
                return ResourceManager.GetString("GDT_SuccessRead_Table_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;rr_table&apos;]//tr[2]/th/span.
        /// </summary>
        internal static string GDT_TableHeader1 {
            get {
                return ResourceManager.GetString("GDT_TableHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[normalize-space()=&apos;Unread Gas Day Take Devices&apos;]/following-sibling::table//table[@class=&apos;standard&apos;]//tr/th/a.
        /// </summary>
        internal static string GDT_TableHeader2 {
            get {
                return ResourceManager.GetString("GDT_TableHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;right&apos;]//a[normalize-space()=&apos;Generate Report&apos;].
        /// </summary>
        internal static string GenerateReport_link {
            get {
                return ResourceManager.GetString("GenerateReport_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;resultsTable&apos;]//table[@class=&apos;standard&apos;]//tr[@class=&apos;odd&apos; or &apos;even&apos; or &apos;even SHORT_INTERVAL_PERIOD&apos;]/td[1].
        /// </summary>
        internal static string IntervalTime {
            get {
                return ResourceManager.GetString("IntervalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;resultsTable&apos;]//table[@class=&apos;standard&apos;]//tr[@class=&apos;odd&apos; or &apos;even&apos; or &apos;even SHORT_INTERVAL_PERIOD&apos;]/td[@class=&apos;numbers&apos;].
        /// </summary>
        internal static string IntervalValue {
            get {
                return ResourceManager.GetString("IntervalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(text(),&apos;Meter Read Report:&apos;)].
        /// </summary>
        internal static string Meter_Read_Report_Details {
            get {
                return ResourceManager.GetString("Meter_Read_Report_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //h3[text()=&apos;Meter Read Report&apos;].
        /// </summary>
        internal static string Meter_Read_Report_Popup {
            get {
                return ResourceManager.GetString("Meter_Read_Report_Popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[text()=&apos;dynamic:&apos;]/following-sibling::span//select.
        /// </summary>
        internal static string Meter_Read_Report_Select {
            get {
                return ResourceManager.GetString("Meter_Read_Report_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;resultstab1&apos;]//table[@class=&apos;standard&apos;]/tbody/tr/th[@class=&apos;up&apos;]/a.
        /// </summary>
        internal static string NSR_AccessPointLink {
            get {
                return ResourceManager.GetString("NSR_AccessPointLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;fs16 fwb mtl mbm left&apos;].
        /// </summary>
        internal static string NSR_Date {
            get {
                return ResourceManager.GetString("NSR_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[text()=&apos;No results&apos;].
        /// </summary>
        internal static string NSR_NoResults {
            get {
                return ResourceManager.GetString("NSR_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[text()=&apos;Network Summary Report&apos;].
        /// </summary>
        internal static string NSR_PageTitle {
            get {
                return ResourceManager.GetString("NSR_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@value=&apos;Refresh Tab&apos;].
        /// </summary>
        internal static string NSR_RefreshButton {
            get {
                return ResourceManager.GetString("NSR_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;resultstab1&apos;]//table[@class=&apos;standard&apos;]/tbody/tr/th/span.
        /// </summary>
        internal static string NSR_TableHeader {
            get {
                return ResourceManager.GetString("NSR_TableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;resultsTable&apos;]//table[@class=&apos;standard&apos;]/tbody//tr/td[1].
        /// </summary>
        internal static string ODR_Result_td {
            get {
                return ResourceManager.GetString("ODR_Result_td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;Read Report&apos;].
        /// </summary>
        internal static string Read_Report_Link {
            get {
                return ResourceManager.GetString("Read_Report_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@class=&apos;combined tar&apos;]//preceding-sibling::td[@class=&apos;tac&apos;]//following::td[1].
        /// </summary>
        internal static string ReadReport_Register_List_Key {
            get {
                return ResourceManager.GetString("ReadReport_Register_List_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;registerResultsTable&apos;]//tbody[@id=&apos;regResults&apos;]/tr/td[@class=&apos;combined tar&apos;].
        /// </summary>
        internal static string ReadReport_Register_List_Val {
            get {
                return ResourceManager.GetString("ReadReport_Register_List_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;registerResultsTable&apos;]//tbody[@id=&apos;regResults&apos;]/tr/td[@rowspan=&apos;6&apos;]/following-sibling::td[@class=&apos;combined tar&apos;].
        /// </summary>
        internal static string ReadReport_Register_List_Val_NewRow {
            get {
                return ResourceManager.GetString("ReadReport_Register_List_Val_NewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;registerResultsTable&apos;]//tbody[@id=&apos;regResults&apos;]/tr/td[@class=&apos;combined tar&apos;]/following-sibling::td[1].
        /// </summary>
        internal static string ReadReport_Register_List_Val1 {
            get {
                return ResourceManager.GetString("ReadReport_Register_List_Val1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;registerResultsTable&apos;]//tbody[@id=&apos;regResults&apos;]/tr/td[@class=&apos;tac&apos;].
        /// </summary>
        internal static string ReadReport_Register_List_Val2 {
            get {
                return ResourceManager.GetString("ReadReport_Register_List_Val2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td//textarea[@name=&apos;reportjob_jobDesc&apos;].
        /// </summary>
        internal static string ReportDesc {
            get {
                return ResourceManager.GetString("ReportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td//input[@name=&apos;reportjob_emailNotifyAddress&apos;].
        /// </summary>
        internal static string ReportEmail {
            get {
                return ResourceManager.GetString("ReportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;mts&apos; and @data-selenium=&apos;ssnui-notification-message&apos;]//a.
        /// </summary>
        internal static string ReportJobId {
            get {
                return ResourceManager.GetString("ReportJobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td//input[@name=&apos;reportjob_jobName&apos;].
        /// </summary>
        internal static string ReportName {
            get {
                return ResourceManager.GetString("ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;popup_button_blue&apos;]//a[normalize-space()=&apos;Generate Report&apos;].
        /// </summary>
        internal static string ReportSubmit {
            get {
                return ResourceManager.GetString("ReportSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;mts&apos; and @data-selenium=&apos;ssnui-notification-message&apos;].
        /// </summary>
        internal static string ReportSucessNotification {
            get {
                return ResourceManager.GetString("ReportSucessNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[normalize-space()=&apos;Requeue Count: ≥&apos;].
        /// </summary>
        internal static string RequeueCount {
            get {
                return ResourceManager.GetString("RequeueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;requeues&apos; and @value=&apos;0&apos;].
        /// </summary>
        internal static string RequeueCountValue {
            get {
                return ResourceManager.GetString("RequeueCountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;label label-success&apos;].
        /// </summary>
        internal static string RunStatusSuccess {
            get {
                return ResourceManager.GetString("RunStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[text()=&apos;Schedule Type:&apos;]/span.
        /// </summary>
        internal static string ScheduleType_label {
            get {
                return ResourceManager.GetString("ScheduleType_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[text()=&apos;dynamic:&apos;]/following-sibling::span/a[contains(@id,&apos;date_link&apos;)].
        /// </summary>
        internal static string StartDate_EndDate_Link {
            get {
                return ResourceManager.GetString("StartDate_EndDate_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[text()=&apos;dynamic:&apos;]/following-sibling::span/a[contains(@id,&apos;time_link&apos;)].
        /// </summary>
        internal static string StartDate_EndDate_ReadReport {
            get {
                return ResourceManager.GetString("StartDate_EndDate_ReadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;View Report&apos;].
        /// </summary>
        internal static string ViewReport_btn {
            get {
                return ResourceManager.GetString("ViewReport_btn", resourceCulture);
            }
        }
    }
}
