//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadEndDynamicXpath.PageXpaths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AMMDevicePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AMMDevicePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeadEndDynamicXpath.PageXpaths.AMMDevicePage", typeof(AMMDevicePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[text()=&apos;Add a meter command&apos;].
        /// </summary>
        internal static string AddMeterCommandButton {
            get {
                return ResourceManager.GetString("AddMeterCommandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[contains(text(),&apos;Status code: SUCCESS&apos;)].
        /// </summary>
        internal static string C12StatusResult {
            get {
                return ResourceManager.GetString("C12StatusResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@class=&quot;datePickerDay&quot;].
        /// </summary>
        internal static string CalenderDate {
            get {
                return ResourceManager.GetString("CalenderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[text()=&apos;Channel 1&apos;].
        /// </summary>
        internal static string Channel1_td {
            get {
                return ResourceManager.GetString("Channel1_td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;deployed&apos;].
        /// </summary>
        internal static string CompleteText {
            get {
                return ResourceManager.GetString("CompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@name=&apos;itron500sconfigjob_configParameters&apos;].
        /// </summary>
        internal static string ConfigOptions {
            get {
                return ResourceManager.GetString("ConfigOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li[@id=&apos;config&apos;]//a.
        /// </summary>
        internal static string Configuration_Page {
            get {
                return ResourceManager.GetString("Configuration_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@id,&apos;DetailsContent&apos;)]//div[@class=&apos;pvs pll&apos;]//label[contains(text(), &quot;Sub-Type:&quot;)].
        /// </summary>
        internal static string DeviceDetails_DeviceType {
            get {
                return ResourceManager.GetString("DeviceDetails_DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li/a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string DeviceOptions {
            get {
                return ResourceManager.GetString("DeviceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string DevicePageButton {
            get {
                return ResourceManager.GetString("DevicePageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;end_date_DatePicker_0_okButton&quot;].
        /// </summary>
        internal static string EndDateOkButton {
            get {
                return ResourceManager.GetString("EndDateOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@data-selenium=&quot;end_date_link&quot;].
        /// </summary>
        internal static string EndTimeRange {
            get {
                return ResourceManager.GetString("EndTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[contains(@id,&apos;end_date_DatePicker_&apos;)]//td[@class=&apos;datePickerDay selectedDate&apos;].
        /// </summary>
        internal static string EndTimeTodayDate {
            get {
                return ResourceManager.GetString("EndTimeTodayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;eventListGroupedTable&apos;]//tr/td/div/a.
        /// </summary>
        internal static string EventsList {
            get {
                return ResourceManager.GetString("EventsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;events&quot;]/a.
        /// </summary>
        internal static string EventsTab {
            get {
                return ResourceManager.GetString("EventsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;odr_results&apos;]//tbody[@id=&apos;regResults&apos;]//tr/td[@class=&apos;tac&apos;].
        /// </summary>
        internal static string GDT_RegVal {
            get {
                return ResourceManager.GetString("GDT_RegVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table/tbody/tr/td/div/div/span/b[text()=&apos;Read Time&apos;]/parent::span.
        /// </summary>
        internal static string GDTReadTime {
            get {
                return ResourceManager.GetString("GDTReadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[contains(text(),&apos;GenericMeterReadData&apos;)].
        /// </summary>
        internal static string GenericMeterReadData {
            get {
                return ResourceManager.GetString("GenericMeterReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string GMRD_Label {
            get {
                return ResourceManager.GetString("GMRD_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr/td[3].
        /// </summary>
        internal static string Interval_Unit_List {
            get {
                return ResourceManager.GetString("Interval_Unit_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr/th.
        /// </summary>
        internal static string IntervalTableHeader {
            get {
                return ResourceManager.GetString("IntervalTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr/td[contains(text(),&apos;pm&apos;) or contains(text(),&apos;am&apos;)].
        /// </summary>
        internal static string IntervalTimeData {
            get {
                return ResourceManager.GetString("IntervalTimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr/td[contains(text(),&apos;pm&apos;) or contains(text(),&apos;am&apos;)].
        /// </summary>
        internal static string IntervalTimeData1 {
            get {
                return ResourceManager.GetString("IntervalTimeData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;odr_results&quot;]/tbody/tr[2]/td[3].
        /// </summary>
        internal static string IntervalTimeFirstRowValue {
            get {
                return ResourceManager.GetString("IntervalTimeFirstRowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;odr_results&quot;]/tbody/tr[3]/td[1].
        /// </summary>
        internal static string IntervalTimeSecondRowValue {
            get {
                return ResourceManager.GetString("IntervalTimeSecondRowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[normalize-space()=&apos;Push results to JMS:&apos;]//following-sibling::*/select.
        /// </summary>
        internal static string JMS_Dropdown {
            get {
                return ResourceManager.GetString("JMS_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;push_to_jms_timeout&apos;]/input.
        /// </summary>
        internal static string JMSTimeoutInput {
            get {
                return ResourceManager.GetString("JMSTimeoutInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;standard&apos;]/tbody/tr/td[@class=&apos;combined tar&apos;].
        /// </summary>
        internal static string Job_Details_ODR_RegList {
            get {
                return ResourceManager.GetString("Job_Details_ODR_RegList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;standard&apos;]/tbody/tr/td[@class=&apos;nowrap &apos;].
        /// </summary>
        internal static string JobDetails_Reg_List {
            get {
                return ResourceManager.GetString("JobDetails_Reg_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr/td.
        /// </summary>
        internal static string JobSubmittedBy_Det {
            get {
                return ResourceManager.GetString("JobSubmittedBy_Det", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[normalize-space()=&apos;Last Run Time&apos;].
        /// </summary>
        internal static string LastRunTime {
            get {
                return ResourceManager.GetString("LastRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;Latest Results&apos;].
        /// </summary>
        internal static string Latest_Results_Link_ODR {
            get {
                return ResourceManager.GetString("Latest_Results_Link_ODR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;register_results&apos;]//tr[2].
        /// </summary>
        internal static string MasterMeterODRResults {
            get {
                return ResourceManager.GetString("MasterMeterODRResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;odr_results_div&apos;]//div.
        /// </summary>
        internal static string NicReadResults {
            get {
                return ResourceManager.GetString("NicReadResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody[@id=&apos;regResults&apos;]/tr/td[@class=&apos;combined tar&apos;]/following::td[position()=1].
        /// </summary>
        internal static string ODR_Immediate_List_Key {
            get {
                return ResourceManager.GetString("ODR_Immediate_List_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody[@id=&apos;regResults&apos;]/tr/td[@class=&apos;combined tar&apos;]/following::td[position()=1].
        /// </summary>
        internal static string ODR_Immediate_List_Key1 {
            get {
                return ResourceManager.GetString("ODR_Immediate_List_Key1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody[@id=&apos;regResults&apos;]/tr/td[@class=&apos;combined tar&apos;].
        /// </summary>
        internal static string ODR_Immediate_List_Val {
            get {
                return ResourceManager.GetString("ODR_Immediate_List_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr/td[@style=&apos;padding-left:2px;&apos;].
        /// </summary>
        internal static string ODR_IntervalRead_LP_Key {
            get {
                return ResourceManager.GetString("ODR_IntervalRead_LP_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr[2]/td[@style=&apos;padding-left:2px;&apos;].
        /// </summary>
        internal static string ODR_IntervalRead_LP_TimeRange_Key_Row1 {
            get {
                return ResourceManager.GetString("ODR_IntervalRead_LP_TimeRange_Key_Row1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr.
        /// </summary>
        internal static string ODR_IntervalRead_LP_TimeRange_Total_Rows {
            get {
                return ResourceManager.GetString("ODR_IntervalRead_LP_TimeRange_Total_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr[2]/td[@class=&apos;align-right blue_bg&apos;].
        /// </summary>
        internal static string ODR_IntervalRead_LP_TimeRange_Val_Row1 {
            get {
                return ResourceManager.GetString("ODR_IntervalRead_LP_TimeRange_Val_Row1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr/td[@class=&apos;align-right blue_bg&apos;].
        /// </summary>
        internal static string ODR_IntervalRead_LP_Val {
            get {
                return ResourceManager.GetString("ODR_IntervalRead_LP_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;detail-health&apos;]//tr//label[text()=&apos;Status:&apos;]/ancestor::td.
        /// </summary>
        internal static string ODR_Job_Status {
            get {
                return ResourceManager.GetString("ODR_Job_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[normalize-space()=&apos;dynamic:&apos;]/following-sibling::span/span.
        /// </summary>
        internal static string ODR_JobDetails_Label_Val {
            get {
                return ResourceManager.GetString("ODR_JobDetails_Label_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr/td[@class=&apos;align-right blue_bg&apos;].
        /// </summary>
        internal static string ODR_NDR_Immediate_List_Val {
            get {
                return ResourceManager.GetString("ODR_NDR_Immediate_List_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]/tbody/tr/td[5].
        /// </summary>
        internal static string ODR_NDR_Immediate_List_Val1 {
            get {
                return ResourceManager.GetString("ODR_NDR_Immediate_List_Val1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;].
        /// </summary>
        internal static string ODR_Result_Table_Link {
            get {
                return ResourceManager.GetString("ODR_Result_Table_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;resultsTable&apos;]//table[@class=&apos;standard&apos;]/tbody//tr/td[1].
        /// </summary>
        internal static string ODR_Result_td {
            get {
                return ResourceManager.GetString("ODR_Result_td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]//tr/td.
        /// </summary>
        internal static string ODR_Result_td1 {
            get {
                return ResourceManager.GetString("ODR_Result_td1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table/tbody[@id=&apos;regResults&apos;]/tr/td[position()=1].
        /// </summary>
        internal static string ODRGDTReadTime {
            get {
                return ResourceManager.GetString("ODRGDTReadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;odr_results&apos;]//tr//th.
        /// </summary>
        internal static string ODRResultsTableHeader {
            get {
                return ResourceManager.GetString("ODRResultsTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;odr_results&apos;]//tr[2].
        /// </summary>
        internal static string ODRResultsTableValue {
            get {
                return ResourceManager.GetString("ODRResultsTableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@class=&quot;paginationbar&quot;]/parent::tr/following-sibling::tr[position()=1].
        /// </summary>
        internal static string ODRResultsTableValueGDT {
            get {
                return ResourceManager.GetString("ODRResultsTableValueGDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //h2[text()=&apos;On Demand Read*&apos;].
        /// </summary>
        internal static string OnDemandRead_Page {
            get {
                return ResourceManager.GetString("OnDemandRead_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;hidden_results&apos;]//h2.
        /// </summary>
        internal static string OnDemandReadHeaderText {
            get {
                return ResourceManager.GetString("OnDemandReadHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;start_date_DatePicker_0_monthPageBackLink&quot;]/img.
        /// </summary>
        internal static string PageBackLink {
            get {
                return ResourceManager.GetString("PageBackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[normalize-space()=&apos;dynamic:&apos;]//parent::div//span//input.
        /// </summary>
        internal static string PeriodInput {
            get {
                return ResourceManager.GetString("PeriodInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@data-selenium=&apos;read_button&apos;].
        /// </summary>
        internal static string ReadButton {
            get {
                return ResourceManager.GetString("ReadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;odr_results&apos;]//tr[@class=&apos;odd&apos;]/td[4].
        /// </summary>
        internal static string ReadResultsChannel1Value {
            get {
                return ResourceManager.GetString("ReadResultsChannel1Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;regResults&quot;]/tr[1]/td[1]/span.
        /// </summary>
        internal static string ReadResultsReadDateValue {
            get {
                return ResourceManager.GetString("ReadResultsReadDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;odr_results&quot;]/tbody/tr[2]/td[1].
        /// </summary>
        internal static string ReadResultsReadTimeValue {
            get {
                return ResourceManager.GetString("ReadResultsReadTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;odr_results&quot;]//tr[@class=&quot;odd&quot;]/td[1].
        /// </summary>
        internal static string ReadResultsStartTimeValue {
            get {
                return ResourceManager.GetString("ReadResultsStartTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;regResults&quot;]/tr[1]/td[3].
        /// </summary>
        internal static string ReadResultsTierValue {
            get {
                return ResourceManager.GetString("ReadResultsTierValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;regResults&quot;]/tr[1]/td[5].
        /// </summary>
        internal static string ReadResultsValue {
            get {
                return ResourceManager.GetString("ReadResultsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[normalize-space()=&apos;Read Scope:&apos;]//following-sibling::span/select.
        /// </summary>
        internal static string ReadScope_dropdown {
            get {
                return ResourceManager.GetString("ReadScope_dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[normalize-space()=&apos;Request Type:&apos;]//following-sibling::span/select.
        /// </summary>
        internal static string ReadType_dropdown {
            get {
                return ResourceManager.GetString("ReadType_dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@data-selenium=&apos;odr_read_type&apos;].
        /// </summary>
        internal static string ReadTypeDropDown {
            get {
                return ResourceManager.GetString("ReadTypeDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@data-selenium=&apos;odr_read_type&apos;]//option[normalize-space()=&apos;dynamic&apos;].
        /// </summary>
        internal static string ReadTypeValue {
            get {
                return ResourceManager.GetString("ReadTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@name=&apos;itron500sconfigjob_requestType&apos;].
        /// </summary>
        internal static string Request_Type {
            get {
                return ResourceManager.GetString("Request_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;provision_results&apos;]//tr[@id=&apos;rp_results_firstrow&apos;]/td[dynamic].
        /// </summary>
        internal static string RSMTableFirstRowValue {
            get {
                return ResourceManager.GetString("RSMTableFirstRowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;provision_results&apos;]//tr/th.
        /// </summary>
        internal static string RSMTableHeader {
            get {
                return ResourceManager.GetString("RSMTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;sending&apos;].
        /// </summary>
        internal static string RunningText {
            get {
                return ResourceManager.GetString("RunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&quot;standard&quot;].
        /// </summary>
        internal static string Scheduled_read_result_table {
            get {
                return ResourceManager.GetString("Scheduled_read_result_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[@class=&quot;paginationbar&quot;]/parent::tr/following-sibling::tr[position()=1].
        /// </summary>
        internal static string Scheduled_Read_Results {
            get {
                return ResourceManager.GetString("Scheduled_Read_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@id=&apos;meterCommandType&apos;].
        /// </summary>
        internal static string SelectMeterCommandDropDown {
            get {
                return ResourceManager.GetString("SelectMeterCommandDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[text()=&apos;Start Date:&apos;]/following-sibling::span/a[contains(@id,&apos;date_link&apos;)].
        /// </summary>
        internal static string StartDate_EndDate_Link1 {
            get {
                return ResourceManager.GetString("StartDate_EndDate_Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;start_date_DatePicker_0_okButton&quot;].
        /// </summary>
        internal static string StartDateOkButton {
            get {
                return ResourceManager.GetString("StartDateOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@data-selenium=&quot;start_date_link&quot;].
        /// </summary>
        internal static string StartTimeRange {
            get {
                return ResourceManager.GetString("StartTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[normalize-space()=&apos;Status:&apos;]//parent::div//span//select.
        /// </summary>
        internal static string Status_Dropdown {
            get {
                return ResourceManager.GetString("Status_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;status_line&apos;]//span[normalize-space()=&apos;dynamic&apos;].
        /// </summary>
        internal static string Status_Line {
            get {
                return ResourceManager.GetString("Status_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@data-selenium=&apos;readTableId&apos;].
        /// </summary>
        internal static string TableIdInputField {
            get {
                return ResourceManager.GetString("TableIdInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[text()=&apos;Threshold:&apos;]//parent::div//span//input.
        /// </summary>
        internal static string ThresholdValue {
            get {
                return ResourceManager.GetString("ThresholdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@data-selenium=&apos;read_time&apos;].
        /// </summary>
        internal static string TimeRangeDropDown {
            get {
                return ResourceManager.GetString("TimeRangeDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[text()=&apos;Time Zone:&apos;]/following-sibling::span/select.
        /// </summary>
        internal static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[text()=&apos;Time Zone:&apos;]/following-sibling::span/select.
        /// </summary>
        internal static string Timezone_Field {
            get {
                return ResourceManager.GetString("Timezone_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@class=&apos;footnote&apos;].
        /// </summary>
        internal static string TotalReadTimeText {
            get {
                return ResourceManager.GetString("TotalReadTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;odr_results_div&apos;]//a.
        /// </summary>
        internal static string ViewEventsLink {
            get {
                return ResourceManager.GetString("ViewEventsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ssnui-notification-content&apos;]//a.
        /// </summary>
        internal static string Warning_JobID {
            get {
                return ResourceManager.GetString("Warning_JobID", resourceCulture);
            }
        }
    }
}
