//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadEndDynamicXpath.PageXpaths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CaasBase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaasBase() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeadEndDynamicXpath.PageXpaths.CaasBase", typeof(CaasBase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;dynamic&apos;].
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;dynamic&apos;].
        /// </summary>
        internal static string CaasLoginInputBox {
            get {
                return ResourceManager.GetString("CaasLoginInputBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;headerDeviceSearch&apos;].
        /// </summary>
        internal static string DeviceQuickSearch {
            get {
                return ResourceManager.GetString("DeviceQuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;device_search_results_table&apos;]//tr/td[@class=&apos;nowrap&apos;]/a[1].
        /// </summary>
        internal static string DeviceSearchResult_FirstRow {
            get {
                return ResourceManager.GetString("DeviceSearchResult_FirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@data-selenium=&apos;appNameLink&apos;].
        /// </summary>
        internal static string MenuLink {
            get {
                return ResourceManager.GetString("MenuLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;apps-container&apos;]/a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string PortalMenu {
            get {
                return ResourceManager.GetString("PortalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;header_search&apos;].
        /// </summary>
        internal static string QuickSearchInput {
            get {
                return ResourceManager.GetString("QuickSearchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@id=&apos;headerSelectMenu&apos;].
        /// </summary>
        internal static string QuickSearchParameterDropDown {
            get {
                return ResourceManager.GetString("QuickSearchParameterDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;ssnui-headerSubNav&apos;]/a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string SubMenu {
            get {
                return ResourceManager.GetString("SubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;menu-item-content&apos;]/span.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
