//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadEndDynamicXpath.PageXpaths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeadEndDynamicXpath.PageXpaths.CreateConfig", typeof(CreateConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[normalize-space()=&apos;dynamic&apos;].
        /// </summary>
        internal static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string ConfigurationParam {
            get {
                return ResourceManager.GetString("ConfigurationParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[text()=&apos;Please select a device class&apos;].
        /// </summary>
        internal static string DeviceClassDropDown {
            get {
                return ResourceManager.GetString("DeviceClassDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul/li[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string DeviceClassDropDownElement {
            get {
                return ResourceManager.GetString("DeviceClassDropDownElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[normalize-space()=&apos;dynamic&apos;]//input.
        /// </summary>
        internal static string Group_Details {
            get {
                return ResourceManager.GetString("Group Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //i[@class=&apos;fa fa-plus&apos;].
        /// </summary>
        internal static string PlusButton {
            get {
                return ResourceManager.GetString("PlusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
