//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadEndDynamicXpath.PageXpaths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeviceEvents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeviceEvents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeadEndDynamicXpath.PageXpaths.DeviceEvents", typeof(DeviceEvents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&quot;standard&quot;]//tr//td[text()=&apos;Event Text:&apos;]/following-sibling::td
        ///.
        /// </summary>
        internal static string EventsListTable_rows {
            get {
                return ResourceManager.GetString("EventsListTable_rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&quot;standard&quot;]//tr//td[@class=&apos;nowrap&apos;]/button.
        /// </summary>
        internal static string EventsListTable_rows_Date {
            get {
                return ResourceManager.GetString("EventsListTable_rows_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&quot;standard&quot;]//tr//td[@class=&apos;nowrap pvs&apos;]/following-sibling::td[contains(text(), &quot;dynamic&quot;)]/preceding-sibling::td[3].
        /// </summary>
        internal static string EventsListTable_rows1 {
            get {
                return ResourceManager.GetString("EventsListTable_rows1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;events&quot;]/a.
        /// </summary>
        internal static string EventsTab {
            get {
                return ResourceManager.GetString("EventsTab", resourceCulture);
            }
        }
    }
}
