//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadEndDynamicXpath.PageXpaths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditConfigGroup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditConfigGroup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeadEndDynamicXpath.PageXpaths.EditConfigGroup", typeof(EditConfigGroup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[text()=&apos;dynamic&apos;]//following-sibling::td/input[@ng-model=&apos;item.event.selected&apos;].
        /// </summary>
        internal static string alarm_chkbx {
            get {
                return ResourceManager.GetString("alarm_chkbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string ConfigGroupList {
            get {
                return ResourceManager.GetString("ConfigGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //h1[contains(@class,&apos;page-title&apos;)].
        /// </summary>
        internal static string ConfigPageTitle {
            get {
                return ResourceManager.GetString("ConfigPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string ConfigurationParam {
            get {
                return ResourceManager.GetString("ConfigurationParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[normalize-space()=&apos;dynamic&apos;]//following-sibling::span//span//span//following-sibling::span.
        /// </summary>
        internal static string DropDown {
            get {
                return ResourceManager.GetString("DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[text()=&apos;dynamic&apos;]/ancestor::tr/td[@ng-if=&apos;showAlarmColumn&apos;]/input[@type=&apos;checkbox&apos;].
        /// </summary>
        internal static string event_chkbx {
            get {
                return ResourceManager.GetString("event_chkbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[normalize-space()=&apos;dynamic&apos;]//preceding-sibling::span/input.
        /// </summary>
        internal static string GenericCheckBox {
            get {
                return ResourceManager.GetString("GenericCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[normalize-space()=&apos;dynamic&apos;]//following-sibling::input.
        /// </summary>
        internal static string GenericCheckBox1 {
            get {
                return ResourceManager.GetString("GenericCheckBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[normalize-space()=&apos;dynamic&apos;]//following-sibling::div/input.
        /// </summary>
        internal static string InputFields {
            get {
                return ResourceManager.GetString("InputFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@aria-hidden=&apos;false&apos;]/li[normalize-space()=&apos;dynamic&apos;].
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //i[@class=&apos;fa fa-plus&apos;].
        /// </summary>
        internal static string PlusButton {
            get {
                return ResourceManager.GetString("PlusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@class=&apos;dateTimePicker&apos;].
        /// </summary>
        internal static string TimesToPush {
            get {
                return ResourceManager.GetString("TimesToPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@class=&apos;model-list&apos;]/li/span.
        /// </summary>
        internal static string TimesToPushElement {
            get {
                return ResourceManager.GetString("TimesToPushElement", resourceCulture);
            }
        }
    }
}
