//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadEndDynamicXpath.PageXpaths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FWUpgrade {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FWUpgrade() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeadEndDynamicXpath.PageXpaths.FWUpgrade", typeof(FWUpgrade).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;upgradeAdd&apos;].
        /// </summary>
        internal static string AddUpgradeLink {
            get {
                return ResourceManager.GetString("AddUpgradeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[normalize-space()=&apos;Email notification(comma separated):&apos;]/following-sibling::td/textarea.
        /// </summary>
        internal static string FWU_AuditJob_Email {
            get {
                return ResourceManager.GetString("FWU_AuditJob_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[normalize-space()=&apos;dynamic:&apos;]/following-sibling::td/input.
        /// </summary>
        internal static string FWU_AuditJob_Input {
            get {
                return ResourceManager.GetString("FWU_AuditJob_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[normalize-space()=&apos;dynamic:&apos;]/following-sibling::td/select.
        /// </summary>
        internal static string FWU_AuditJob_Select {
            get {
                return ResourceManager.GetString("FWU_AuditJob_Select", resourceCulture);
            }
        }
    }
}
