//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadEndDynamicXpath.PageXpaths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MeterProgramConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeterProgramConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeadEndDynamicXpath.PageXpaths.MeterProgramConfig", typeof(MeterProgramConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[normalize-space()=&apos;dynamic&apos;]/ancestor::tr/td[contains(@id,&apos;projectDevice.netDeviceName&apos;)]/a.
        /// </summary>
        internal static string DeviceLinkWithMac {
            get {
                return ResourceManager.GetString("DeviceLinkWithMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[contains(@id,&apos;projectDevice.netDeviceName&apos;)].
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[contains(@id,&apos;projectDevice.nicMacID&apos;)].
        /// </summary>
        internal static string DevicesMacIdList {
            get {
                return ResourceManager.GetString("DevicesMacIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string MPCTabs {
            get {
                return ResourceManager.GetString("MPCTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[text() = &apos;Operational State:&apos;]//following-sibling::span.
        /// </summary>
        internal static string OpState {
            get {
                return ResourceManager.GetString("OpState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string ProgramLink {
            get {
                return ResourceManager.GetString("ProgramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
    }
}
