//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadEndDynamicXpath.PageXpaths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NCDevicesPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NCDevicesPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeadEndDynamicXpath.PageXpaths.NCDevicesPage", typeof(NCDevicesPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;Device Name&apos;]//parent::th//parent::tr//following-sibling::th//input.
        /// </summary>
        internal static string Checkbox {
            get {
                return ResourceManager.GetString("Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //translate[text()=&apos;Create a Dynamic Device Group&apos;].
        /// </summary>
        internal static string CreateDynamicDeviceGroup {
            get {
                return ResourceManager.GetString("CreateDynamicDeviceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //translate[text()=&apos;Create a Static Device Group&apos;].
        /// </summary>
        internal static string CreateStaticDeviceGroup {
            get {
                return ResourceManager.GetString("CreateStaticDeviceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-selenium=&apos;device-attribute-name&apos;]/md-select.
        /// </summary>
        internal static string DeviceAttributeSelectDropDown {
            get {
                return ResourceManager.GetString("DeviceAttributeSelectDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //translate[text()=&apos;dynamic&apos;]//parent::div//parent::md-option.
        /// </summary>
        internal static string DeviceAttributeValue {
            get {
                return ResourceManager.GetString("DeviceAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[text()=&apos;dynamic&apos;]//parent::md-option.
        /// </summary>
        internal static string DeviceAttributeValueBool {
            get {
                return ResourceManager.GetString("DeviceAttributeValueBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-selenium=&apos;device-attribute-value&apos;]//span//md-select.
        /// </summary>
        internal static string DeviceAttributeValueSelectDropDown {
            get {
                return ResourceManager.GetString("DeviceAttributeValueSelectDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[text()=&apos;dynamic&apos;]//parent::md-option.
        /// </summary>
        internal static string DeviceSearchAttribute {
            get {
                return ResourceManager.GetString("DeviceSearchAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-selenium=&apos;device-attribute-value&apos;]//input.
        /// </summary>
        internal static string DeviceSearchEdit {
            get {
                return ResourceManager.GetString("DeviceSearchEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[normalize-space()=&apos;Dynamic Groups&apos;].
        /// </summary>
        internal static string DynamicGroupPage {
            get {
                return ResourceManager.GetString("DynamicGroupPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;displayTableCell&apos;]/div[@class=&apos;displayTableRow&apos;].
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;dynamic&apos;].
        /// </summary>
        internal static string GroupPresent {
            get {
                return ResourceManager.GetString("GroupPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td[text()=&apos;dynamic&apos;]/following-sibling::td/button[normalize-space()=&apos;view&apos;].
        /// </summary>
        internal static string ImportValidation {
            get {
                return ResourceManager.GetString("ImportValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[normalize-space()=&apos;dynamic&apos;].
        /// </summary>
        internal static string NCJobButton {
            get {
                return ResourceManager.GetString("NCJobButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;alert alert-nc-success alert-dismissible&apos;].
        /// </summary>
        internal static string NotificationMessage {
            get {
                return ResourceManager.GetString("NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //nc-site-menu//*[text()[normalize-space()=&apos;dynamic&apos;]].
        /// </summary>
        internal static string SideTabName {
            get {
                return ResourceManager.GetString("SideTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[normalize-space()=&apos;Static Groups&apos;].
        /// </summary>
        internal static string StaticGroupPage {
            get {
                return ResourceManager.GetString("StaticGroupPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
